name: test-and-publish
on:
  push:
    branches:
      - develop
jobs:
  openergy:
    uses: openergy/ogithub-actions/.github/workflows/opypackage-standard-v02.yml@master
    with:
      publish-to-pypi: true
    secrets:
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      PYPI_OPENERGY_PASSWORD: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
